site_name: Pipelex API Documentation

site_url: https://pipelex.github.io/pipelex-api/
site_description: "Official API documentation for Pipelex - REST API for executing Pipelex pipelines and validating PLX files"
docs_dir: docs
repo_url: "https://github.com/Pipelex/pipelex"
repo_name: "Pipelex on GitHub"

theme:
  name: material
  favicon: https://pipelex-web.s3.amazonaws.com/logo/pipelex-favicon-32.png
  logo: https://pipelex-web.s3.amazonaws.com/logo/Pipelex-logo-wot-mono-560x176.png
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
  palette:
    - scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

copyright: "© 2025 Evotis S.A.S. <br/>Pipelex is a trademark of Evotis S.A.S."

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Pipelex/pipelex
      name: Pipelex on GitHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pipelex/
      name: pipelex on PyPI
    - icon: fontawesome/brands/twitter
      link: https://x.com/PipelexAI
      name: Pipelex on X
    - icon: fontawesome/brands/discord
      link: https://go.pipelex.com/discord
      name: Pipelex on Discord
  generator: false

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details

nav:
  - Home: https://docs.pipelex.com/
  - API Reference:
    - Getting Started: index.md
  - n8n Node: https://pipelex.github.io/n8n-nodes-pipelex/
  - Configuration: https://docs.pipelex.com/pages/configuration/
  - Development: https://docs.pipelex.com/pages/tools/

extra_css:
  - stylesheets/general.css

